import type { Metadata } from 'next'
import './globals.css'
import Script from 'next/script'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ko'>
      <head></head>
      <body>{children}</body>
      <Script src='https://cdn.jsdelivr.net/npm/page-flip/dist/js/page-flip.browser.js' />
      <Script
        async
        src='https://t1.kakaocdn.net/kakao_js_sdk/2.7.4/kakao.min.js'
        integrity='sha384-DKYJZ8NLiK8MN4/C5P2dtSmLQ4KwPaoqAfyA/DfmEc1VDxu4yyC7wy6K1Hs90nka'
        crossOrigin='anonymous'
      />
    </html>
  )
}
